export const faqsData = [
  {
    question: "What are Babbling Baboons Club NFTs?",
    answer: ["Babbling Baboons Club NFTs are a collection of 2,222 digital art pieces of Baboons minted on the" +
    " Ethereum blockchain. Owning a Babbling Baboons Club NFT will give you access to very exclusive events and" +
    " features : P2E Blockchain game, percentage of royalties, community DAO, Exclusive Babbling Baboons Club Merchandise and Giveaways and a free access to part 2…"]
  },
  {
    question: "How many Traits and Attributes?",
    answer: ["Our unique collection has 7 total properties and 54 traits based around the most Babbling Baboons. Which one will you catch?"]
  },
  {
    question: "Are the NFTs unique?",
    answer: ["Yes. The NFTs are ERC-721 compliant, and each is algorithmically generated by combining 50+ unique" +
    " traits with 7 variables. (Background, Fur, Bottom, Clothes, Teeth, Eyes and Hats) Some rarer than others.","When will I be able to own my own Babbling Baboons Club NFT?","The Baboons will be able to be caught late January, no specific date yet."]
  },
  {
    question: "What is the cost of a mint?",
    answer: ["The cost to mint 1 Babbling Baboons will be 0.04 eth + gas","How can I get in touch?","Follow us on Discord, Twitter, and Instagram. The best place for regular updates and announcements is the Babbling Baboons Club Discord!"]
  },
]